import { createSlice } from "@reduxjs/toolkit";

const translations = {
    en: {
        CINEMOOD: "CINEMOOD",
        moodSearch: "Mood Search",
        selectLanguage: "Select Language",
        MoreInfo: "More Info",
        AllRightsReserved: "All Rights Reserved",
        TrendingMovies: "Trending Movies",
        TrendingTVShows: "Trending TV Shows",
        NowPlaying: "Now Playing",
        Popular: "Popular",
        TopRated: "Top-Rated",
        Search: "Search",
        Whatwouldyouliketoseetoday: "What would you like to see today?",
        WatchonYouTube: "Watch on YouTube",
        AddtoLibrary: "Add to Library",
        CreatePlaylist: "Create Playlist",
        Cancel: "Cancel",
        Done: "Done",
        TitleNotAvailable: "Title Not Available",
        Notaglineavailable: "No tagline available",
        Nodescriptionavailableforthismovie: "No description available for this movie.",
        NoRating: "No Rating",
        RuntimeUnknown: "Runtime Unknown",
        ReleaseDateUnavailable: "Release Date Unavailable",
        MyLibrary: "My Library",
        Nomoviesaddedtothisplaylistyet: "No movies added to this playlist yet.",
        Delete: "Delete",
        Noplaylistsavailable: "No playlists available.",
        NeedHelp: "Need Help",
        Library: "Library",
        Signout: "Signout",
        UserName: "User Name",
        EmailAddress: "Email Address",
        Password: "Password",
        SignIn: "Sign In",
        SignUp: "Sign Up",
        NewtoNetflix: "New to Netflix?",
        AlreadyRegistered: "Already Registered?",
        NewPlaylistName: "New Playlist Name",
    },
    hi: {
        CINEMOOD: "सिनेमूड",
        moodSearch: "मूड खोज",
        selectLanguage: "भाषा चुनें",
        MoreInfo: "और जानकारी",
        AllRightsReserved: "सर्वाधिकार सुरक्षित",
        TrendingMovies: "ट्रेंडिंग फिल्में",
        TrendingTVShows: "ट्रेंडिंग टीवी शो",
        NowPlaying: "अभी चल रहा है",
        Popular: "लोकप्रिय",
        TopRated: "शीर्ष रेटेड",
        Search: "खोजें",
        Whatwouldyouliketoseetoday: "आज आप क्या देखना चाहेंगे?",
        WatchonYouTube: "यूट्यूब पर देखें",
        AddtoLibrary: "लाइब्रेरी में जोड़ें",
        CreatePlaylist: "प्लेलिस्ट बनाएं",
        Cancel: "रद्द करें",
        Done: "हो गया",
        TitleNotAvailable: "शीर्षक उपलब्ध नहीं",
        Notaglineavailable: "कोई टैगलाइन उपलब्ध नहीं",
        Nodescriptionavailableforthismovie: "इस फिल्म के लिए कोई विवरण उपलब्ध नहीं है।",
        NoRating: "कोई रेटिंग नहीं",
        RuntimeUnknown: "समय अज्ञात",
        ReleaseDateUnavailable: "रिलीज़ तिथि उपलब्ध नहीं",
        MyLibrary: "मेरी लाइब्रेरी",
        Nomoviesaddedtothisplaylistyet: "इस प्लेलिस्ट में अभी तक कोई फिल्म नहीं जोड़ी गई है।",
        Delete: "हटाएं",
        Noplaylistsavailable: "कोई प्लेलिस्ट उपलब्ध नहीं।",
        NeedHelp: "मदद चाहिए",
        Library: "लाइब्रेरी",
        Signout: "साइन आउट",
        UserName: "उपयोगकर्ता नाम",
        EmailAddress: "ईमेल पता",
        Password: "पासवर्ड",
        SignIn: "साइन इन करें",
        SignUp: "साइन अप करें",
        NewtoNetflix: "नेटफ्लिक्स पर नए हैं?",
        AlreadyRegistered: "पहले से ही पंजीकृत?",
        NewPlaylistName: "नई प्लेलिस्ट का नाम",
    },
    gu: {
        CINEMOOD: "સિનેમૂડ",
        moodSearch: "મૂડ શોધ",
        selectLanguage: "ભાષા પસંદ કરો",
        MoreInfo: "વધુ માહિતી",
        AllRightsReserved: "સર્વાધિકાર સુરક્ષિત",
        TrendingMovies: "ટ્રેન્ડિંગ ફિલ્મો",
        TrendingTVShows: "ટ્રેન્ડિંગ ટીવી શો",
        NowPlaying: "હાલ રમાઈ રહ્યું છે",
        Popular: "લોકપ્રિય",
        TopRated: "ઉચ્ચ રેટેડ",
        Search: "શોધ",
        Whatwouldyouliketoseetoday: "તમે આજે શું જોવું પસંદ કરશો?",
        WatchonYouTube: "યુટ્યુબ પર જુઓ",
        AddtoLibrary: "લાઇબ્રેરીમાં ઉમેરો",
        CreatePlaylist: "પ્લેલિસ્ટ બનાવો",
        Cancel: "રદ કરો",
        Done: "થઈ ગયું",
        TitleNotAvailable: "શીર્ષક ઉપલબ્ધ નથી",
        Notaglineavailable: "કોઈ ટેગલાઇન ઉપલબ્ધ નથી",
        Nodescriptionavailableforthismovie: "આ ફિલ્મ માટે કોઈ વર્ણન ઉપલબ્ધ નથી.",
        NoRating: "કોઈ રેટિંગ નથી",
        RuntimeUnknown: "સમય અજ્ઞાત",
        ReleaseDateUnavailable: "પ્રકાશન તારીખ ઉપલબ્ધ નથી",
        MyLibrary: "મારી લાઇબ્રેરી",
        Nomoviesaddedtothisplaylistyet: "આ પ્લેલિસ્ટમાં હજુ સુધી કોઈ ફિલ્મ ઉમેરાઈ નથી.",
        Delete: "કાઢી નાંખો",
        Noplaylistsavailable: "કોઈ પ્લેલિસ્ટ ઉપલબ્ધ નથી.",
        NeedHelp: "મદદ જોઈએ",
        Library: "લાઇબ્રેરી",
        Signout: "સાઇન આઉટ",
        UserName: "વપરાશકર્તા નામ",
        EmailAddress: "ઈમેલ સરનામું",
        Password: "પાસવર્ડ",
        SignIn: "સાઇન ઇન",
        SignUp: "સાઇન અપ",
        NewtoNetflix: "નેટફ્લિક્સ માટે નવું છે?",
        AlreadyRegistered: "પહેલેથી જ નોંધાયેલ?",
        NewPlaylistName: "નવી પ્લેલિસ્ટ નામ",
    },
    es: {
        CINEMOOD: "CINEMOOD",
        moodSearch: "Búsqueda por estado de ánimo",
        selectLanguage: "Seleccionar idioma",
        MoreInfo: "Más información",
        AllRightsReserved: "Todos los derechos reservados",
        TrendingMovies: "Películas en tendencia",
        TrendingTVShows: "Series de TV en tendencia",
        NowPlaying: "En reproducción",
        Popular: "Popular",
        TopRated: "Mejor valorado",
        Search: "Buscar",
        Whatwouldyouliketoseetoday: "¿Qué te gustaría ver hoy?",
        WatchonYouTube: "Ver en YouTube",
        AddtoLibrary: "Agregar a la biblioteca",
        CreatePlaylist: "Crear lista de reproducción",
        Cancel: "Cancelar",
        Done: "Hecho",
        TitleNotAvailable: "Título no disponible",
        Notaglineavailable: "No hay lema disponible",
        Nodescriptionavailableforthismovie: "No hay descripción disponible para esta película.",
        NoRating: "Sin calificación",
        RuntimeUnknown: "Duración desconocida",
        ReleaseDateUnavailable: "Fecha de estreno no disponible",
        MyLibrary: "Mi biblioteca",
        Nomoviesaddedtothisplaylistyet: "Aún no se han agregado películas a esta lista de reproducción.",
        Delete: "Eliminar",
        Noplaylistsavailable: "No hay listas de reproducción disponibles.",
        NeedHelp: "¿Necesitas ayuda?",
        Library: "Biblioteca",
        Signout: "Cerrar sesión",
        UserName: "Nombre de usuario",
        EmailAddress: "Correo electrónico",
        Password: "Contraseña",
        SignIn: "Iniciar sesión",
        SignUp: "Registrarse",
        NewtoNetflix: "¿Nuevo en Netflix?",
        AlreadyRegistered: "¿Ya registrado?",
        NewPlaylistName: "Nuevo nombre de lista de reproducción",
    },    
    fr: {
        CINEMOOD: "CINÉMOOD",
        moodSearch: "Recherche d'humeur",
        selectLanguage: "Choisir la langue",
        MoreInfo: "Plus d'informations",
        AllRightsReserved: "Tous droits réservés",
        TrendingMovies: "Films tendances",
        TrendingTVShows: "Émissions TV tendances",
        NowPlaying: "En cours de lecture",
        Popular: "Populaire",
        TopRated: "Le mieux noté",
        Search: "Rechercher",
        Whatwouldyouliketoseetoday: "Que souhaitez-vous voir aujourd'hui?",
        WatchonYouTube: "Regarder sur YouTube",
        AddtoLibrary: "Ajouter à la bibliothèque",
        CreatePlaylist: "Créer une playlist",
        Cancel: "Annuler",
        Done: "Terminé",
        TitleNotAvailable: "Titre non disponible",
        Notaglineavailable: "Aucune accroche disponible",
        Nodescriptionavailableforthismovie: "Aucune description disponible pour ce film.",
        NoRating: "Pas de note",
        RuntimeUnknown: "Durée inconnue",
        ReleaseDateUnavailable: "Date de sortie indisponible",
        MyLibrary: "Ma bibliothèque",
        Nomoviesaddedtothisplaylistyet: "Aucun film ajouté à cette playlist pour le moment.",
        Delete: "Supprimer",
        Noplaylistsavailable: "Aucune playlist disponible.",
        NeedHelp: "Besoin d'aide",
        Library: "Bibliothèque",
        Signout: "Se déconnecter",
        UserName: "Nom d'utilisateur",
        EmailAddress: "Adresse e-mail",
        Password: "Mot de passe",
        SignIn: "Se connecter",
        SignUp: "S'inscrire",
        NewtoNetflix: "Nouveau sur Netflix?",
        AlreadyRegistered: "Déjà inscrit?",
        NewPlaylistName: "Nouveau nom de playlist",
    },
};

const languageSlice = createSlice({
    name: "language",
    initialState: { currentLanguage: "en", translations: translations.en },
    reducers: { 
        changeLanguage: (state, action) => { 
            state.currentLanguage = action.payload; 
            state.translations = translations[action.payload]; 
        } 
    }
});

export const { changeLanguage } = languageSlice.actions;
export default languageSlice.reducer;
