import { createSlice } from "@reduxjs/toolkit";

const translations = {
    en: {
        CINEMOOD: "CINEMOOD",
        moodSearch: "My Mentor",
        selectLanguage: "Select Language",
        MoreInfo: "More Info",
        AllRightsReserved: "All Rights Reserved",
        TrendingMovies: "Trending Movies",
        TrendingTVShows: "Trending TV Shows",
        NowPlaying: "Now Playing",
        Popular: "Popular",
        TopRated: "Top-Rated",
        Search: "Search",
        Whatwouldyouliketoseetoday: "What would you like to see today?",
        WatchonYouTube: "Watch on YouTube",
        AddtoLibrary: "Add to Library",
        CreatePlaylist: "Create Watchlist",
        Cancel: "Cancel",
        Done: "Done",
        TitleNotAvailable: "Title Not Available",
        Notaglineavailable: "No tagline available",
        Nodescriptionavailableforthismovie: "No description available for this movie.",
        NoRating: "No Rating",
        RuntimeUnknown: "Runtime Unknown",
        ReleaseDateUnavailable: "Release Date Unavailable",
        MyLibrary: "My Library",
        Nomoviesaddedtothisplaylistyet: "No movies added to this watchlist yet.",
        Delete: "Delete",
        Noplaylistsavailable: "No watchlists available.",
        NeedHelp: "Need Help",
        Library: "Library",
        Signout: "Signout",
        UserName: "User Name",
        EmailAddress: "Email Address",
        Password: "Password",
        SignIn: "Sign In",
        SignUp: "Sign Up",
        NewtoNetflix: "New to Netflix?",
        AlreadyRegistered: "Already Registered?",
        NewPlaylistName: "New Watchlist Name",
        tagLine1 : "Welcome to Your Ultimate Streaming Experience",
        tagLine2:"Discover a world of entertainment, personalized recommendations, and an immersive viewing experience.",
        GetStarted:"Get Started",
        HowItWorks:"How It Works",
        tagLine001:"1. Create an Account",
        tagLine01:"Sign up with your email and password to start exploring.",
        tagLine002:"2. Personalize Your Experience",
        tagLine02:"Set your preferences and get personalized recommendations tailored for you.",
        tagLine003:"3. Build Your Watchlist",
        tagLine03:"Save your favorite movies and shows to watch later with ease.",
        ConfirmPassword:"Confirm Password",
        Watchlistnamecannotbeempty:"Watchlist name cannot be empty."
    },
    hi: {
        CINEMOOD: "सिनेमूड",
        moodSearch: "मूड खोज",
        selectLanguage: "भाषा चुनें",
        MoreInfo: "और जानकारी",
        AllRightsReserved: "सर्वाधिकार सुरक्षित",
        TrendingMovies: "ट्रेंडिंग फिल्में",
        TrendingTVShows: "ट्रेंडिंग टीवी शो",
        NowPlaying: "अभी चल रहा है",
        Popular: "लोकप्रिय",
        TopRated: "शीर्ष रेटेड",
        Search: "खोजें",
        Whatwouldyouliketoseetoday: "आज आप क्या देखना चाहेंगे?",
        WatchonYouTube: "यूट्यूब पर देखें",
        AddtoLibrary: "लाइब्रेरी में जोड़ें",
        CreatePlaylist: "वॉचलिस्ट बनाएं",
        Cancel: "रद्द करें",
        Done: "हो गया",
        TitleNotAvailable: "शीर्षक उपलब्ध नहीं",
        Notaglineavailable: "कोई टैगलाइन उपलब्ध नहीं",
        Nodescriptionavailableforthismovie: "इस फिल्म के लिए कोई विवरण उपलब्ध नहीं है।",
        NoRating: "कोई रेटिंग नहीं",
        RuntimeUnknown: "समय अज्ञात",
        ReleaseDateUnavailable: "रिलीज़ तिथि उपलब्ध नहीं",
        MyLibrary: "मेरी लाइब्रेरी",
        Nomoviesaddedtothisplaylistyet: "इस वॉचलिस्ट में अभी तक कोई फिल्म नहीं जोड़ी गई है।",
        Delete: "हटाएं",
        Noplaylistsavailable: "कोई वॉचलिस्ट उपलब्ध नहीं।",
        NeedHelp: "मदद चाहिए",
        Library: "लाइब्रेरी",
        Signout: "साइन आउट",
        UserName: "उपयोगकर्ता नाम",
        EmailAddress: "ईमेल पता",
        Password: "पासवर्ड",
        SignIn: "साइन इन करें",
        SignUp: "साइन अप करें",
        NewtoNetflix: "नेटफ्लिक्स पर नए हैं?",
        AlreadyRegistered: "पहले से ही पंजीकृत?",
        NewPlaylistName: "नई वॉचलिस्ट का नाम",
        tagLine1: "आपके परम स्ट्रीमिंग अनुभव में आपका स्वागत है",
        tagLine2: "मनोरंजन की दुनिया की खोज करें, व्यक्तिगत अनुशंसाएँ प्राप्त करें, और एक इमर्सिव देखने का अनुभव लें।",
        GetStarted: "शुरू करें",
        HowItWorks: "यह कैसे काम करता है",
        tagLine001: "१. एक खाता बनाएँ",
        tagLine01: "अन्वेषण शुरू करने के लिए अपने ईमेल और पासवर्ड के साथ साइन अप करें।",
        tagLine002: "२. अपने अनुभव को व्यक्तिगत बनाएं",
        tagLine02: "अपनी पसंद सेट करें और आपके लिए तैयार की गई व्यक्तिगत अनुशंसाएँ प्राप्त करें।",
        tagLine003: "३. अपनी वॉचलिस्ट बनाएं",
        tagLine03: "अपने पसंदीदा फ़िल्में और शो को बाद में देखने के लिए आसानी से सहेजें।",
        ConfirmPassword:"पासवर्ड की पुष्टि करें"
    },
    gu: {
        CINEMOOD: "સિનેમૂડ",
        moodSearch: "મૂડ શોધ",
        selectLanguage: "ભાષા પસંદ કરો",
        MoreInfo: "વધુ માહિતી",
        AllRightsReserved: "સર્વાધિકાર સુરક્ષિત",
        TrendingMovies: "ટ્રેન્ડિંગ ફિલ્મો",
        TrendingTVShows: "ટ્રેન્ડિંગ ટીવી શો",
        NowPlaying: "હાલ રમાઈ રહ્યું છે",
        Popular: "લોકપ્રિય",
        TopRated: "ઉચ્ચ રેટેડ",
        Search: "શોધ",
        Whatwouldyouliketoseetoday: "તમે આજે શું જોવું પસંદ કરશો?",
        WatchonYouTube: "યુટ્યુબ પર જુઓ",
        AddtoLibrary: "લાઇબ્રેરીમાં ઉમેરો",
        CreatePlaylist: "વૉચલિસ્ટ બનાવો",
        Cancel: "રદ કરો",
        Done: "થઈ ગયું",
        TitleNotAvailable: "શીર્ષક ઉપલબ્ધ નથી",
        Notaglineavailable: "કોઈ ટેગલાઇન ઉપલબ્ધ નથી",
        Nodescriptionavailableforthismovie: "આ ફિલ્મ માટે કોઈ વર્ણન ઉપલબ્ધ નથી.",
        NoRating: "કોઈ રેટિંગ નથી",
        RuntimeUnknown: "સમય અજ્ઞાત",
        ReleaseDateUnavailable: "પ્રકાશન તારીખ ઉપલબ્ધ નથી",
        MyLibrary: "મારી લાઇબ્રેરી",
        Nomoviesaddedtothisplaylistyet: "આ વૉચલિસ્ટમાં હજુ સુધી કોઈ ફિલ્મ ઉમેરાઈ નથી.",
        Delete: "કાઢી નાંખો",
        Noplaylistsavailable: "કોઈ વૉચલિસ્ટ ઉપલબ્ધ નથી.",
        NeedHelp: "મદદ જોઈએ",
        Library: "લાઇબ્રેરી",
        Signout: "સાઇન આઉટ",
        UserName: "વપરાશકર્તા નામ",
        EmailAddress: "ઈમેલ સરનામું",
        Password: "પાસવર્ડ",
        SignIn: "સાઇન ઇન",
        SignUp: "સાઇન અપ",
        NewtoNetflix: "નેટફ્લિક્સ માટે નવું છે?",
        AlreadyRegistered: "પહેલેથી જ નોંધાયેલ?",
        NewPlaylistName: "નવી વૉચલિસ્ટનું નામ",
        tagLine1: "તમારા અંતિમ સ્ટ્રીમિંગ અનુભવમાં આપનું સ્વાગત છે",
        tagLine2: "મનોરંજનની દુનિયાની શોધ કરો, વ્યક્તિગત ભલામણો મેળવો અને એક આકર્ષક દર્શન અનુભવ માણો.",
        GetStarted: "પ્રારંભ કરો",
        HowItWorks: "એ કેવી રીતે કામ કરે છે",
        tagLine001: "૧. એક એકાઉન્ટ બનાવો",
        tagLine01: "અન્વેષણ શરૂ કરવા માટે તમારા ઈમેલ અને પાસવર્ડથી સાઇન અપ કરો.",
        tagLine002: "૨. તમારો અનુભવ વ્યક્તિગત બનાવો",
        tagLine02: "તમારી પસંદગીઓ સેટ કરો અને તમારા માટે તૈયાર કરેલી વ્યક્તિગત ભલામણો મેળવો.",
        tagLine003: "૩. તમારી વૉચલિસ્ટ બનાવો",
        tagLine03: "તમારા મનપસંદ મૂવી અને શો પછીથી જોવા માટે સરળતાથી સંગ્રહિત કરો.",
        ConfirmPassword:"પાસવર્ડની પુષ્ટિ કરો"
    },
    es: {
        CINEMOOD: "CINEMOOD",
        moodSearch: "Búsqueda por estado de ánimo",
        selectLanguage: "Seleccionar idioma",
        MoreInfo: "Más información",
        AllRightsReserved: "Todos los derechos reservados",
        TrendingMovies: "Películas en tendencia",
        TrendingTVShows: "Series de TV en tendencia",
        NowPlaying: "En reproducción",
        Popular: "Popular",
        TopRated: "Mejor valorado",
        Search: "Buscar",
        Whatwouldyouliketoseetoday: "¿Qué te gustaría ver hoy?",
        WatchonYouTube: "Ver en YouTube",
        AddtoLibrary: "Agregar a la biblioteca",
        CreatePlaylist: "Crear lista de reproducción",
        Cancel: "Cancelar",
        Done: "Hecho",
        TitleNotAvailable: "Título no disponible",
        Notaglineavailable: "No hay lema disponible",
        Nodescriptionavailableforthismovie: "No hay descripción disponible para esta película.",
        NoRating: "Sin calificación",
        RuntimeUnknown: "Duración desconocida",
        ReleaseDateUnavailable: "Fecha de estreno no disponible",
        MyLibrary: "Mi biblioteca",
        Nomoviesaddedtothisplaylistyet: "Aún no se han agregado películas a esta lista de reproducción.",
        Delete: "Eliminar",
        Noplaylistsavailable: "No hay listas de reproducción disponibles.",
        NeedHelp: "¿Necesitas ayuda?",
        Library: "Biblioteca",
        Signout: "Cerrar sesión",
        UserName: "Nombre de usuario",
        EmailAddress: "Correo electrónico",
        Password: "Contraseña",
        SignIn: "Iniciar sesión",
        SignUp: "Registrarse",
        NewtoNetflix: "¿Nuevo en Netflix?",
        AlreadyRegistered: "¿Ya registrado?",
        NewPlaylistName: "Nuevo nombre de la lista de seguimiento",
        tagLine1: "Bienvenido a tu experiencia de streaming definitiva",
        tagLine2: "Descubre un mundo de entretenimiento, recomendaciones personalizadas y una experiencia de visualización inmersiva.",
        GetStarted: "Comenzar",
        HowItWorks: "Cómo funciona",
        tagLine001: "1. Crea una cuenta",
        tagLine01: "Regístrate con tu correo electrónico y contraseña para empezar a explorar.",
        tagLine002: "2. Personaliza tu experiencia",
        tagLine02: "Configura tus preferencias y obtén recomendaciones personalizadas solo para ti.",
        tagLine003: "3. Construye tu lista de seguimiento",
        tagLine03: "Guarda tus películas y programas favoritos para verlos más tarde con facilidad.",
        ConfirmPassword:"Confirmar contraseña"
    },    
    fr: {
        CINEMOOD: "CINÉMOOD",
        moodSearch: "Recherche d'humeur",
        selectLanguage: "Choisir la langue",
        MoreInfo: "Plus d'informations",
        AllRightsReserved: "Tous droits réservés",
        TrendingMovies: "Films tendances",
        TrendingTVShows: "Émissions TV tendances",
        NowPlaying: "En cours de lecture",
        Popular: "Populaire",
        TopRated: "Le mieux noté",
        Search: "Rechercher",
        Whatwouldyouliketoseetoday: "Que souhaitez-vous voir aujourd'hui?",
        WatchonYouTube: "Regarder sur YouTube",
        AddtoLibrary: "Ajouter à la bibliothèque",
        CreatePlaylist: "Créer une playlist",
        Cancel: "Annuler",
        Done: "Terminé",
        TitleNotAvailable: "Titre non disponible",
        Notaglineavailable: "Aucune accroche disponible",
        Nodescriptionavailableforthismovie: "Aucune description disponible pour ce film.",
        NoRating: "Pas de note",
        RuntimeUnknown: "Durée inconnue",
        ReleaseDateUnavailable: "Date de sortie indisponible",
        MyLibrary: "Ma bibliothèque",
        Nomoviesaddedtothisplaylistyet: "Aucun film ajouté à cette playlist pour le moment.",
        Delete: "Supprimer",
        Noplaylistsavailable: "Aucune playlist disponible.",
        NeedHelp: "Besoin d'aide",
        Library: "Bibliothèque",
        Signout: "Se déconnecter",
        UserName: "Nom d'utilisateur",
        EmailAddress: "Adresse e-mail",
        Password: "Mot de passe",
        SignIn: "Se connecter",
        SignUp: "S'inscrire",
        NewtoNetflix: "Nouveau sur Netflix?",
        AlreadyRegistered: "Déjà inscrit?",
        NewPlaylistName: "Nouveau nom de liste de surveillance",
        tagLine1: "Bienvenue dans votre expérience de streaming ultime",
        tagLine2: "Découvrez un monde de divertissement, des recommandations personnalisées et une expérience de visionnage immersive.",
        GetStarted: "Commencer",
        HowItWorks: "Comment ça marche",
        tagLine001: "1. Créez un compte",
        tagLine01: "Inscrivez-vous avec votre e-mail et votre mot de passe pour commencer à explorer.",
        tagLine002: "2. Personnalisez votre expérience",
        tagLine02: "Définissez vos préférences et obtenez des recommandations personnalisées adaptées à vous.",
        tagLine003: "3. Créez votre liste de surveillance",
        tagLine03: "Enregistrez vos films et émissions préférés pour les regarder plus tard facilement.",
        ConfirmPassword:"Confirmer le mot de passe",
    },
};

const languageSlice = createSlice({
    name: "language",
    initialState: { currentLanguage: "en", translations: translations.en },
    reducers: { 
        changeLanguage: (state, action) => { 
            state.currentLanguage = action.payload; 
            state.translations = translations[action.payload]; 
        } 
    }
});

export const { changeLanguage } = languageSlice.actions;
export default languageSlice.reducer;
